export const ERROR_CODES = {

  AUTH: {
    INVALID_CREDENTIALS: 'AUTH_001',
    INVALID_REFRESH_TOKEN: 'AUTH_002',
    USER_INACTIVE: 'AUTH_003',
    SESSION_EXPIRED: 'AUTH_004',
    SESSION_REVOKED: 'AUTH_005',
  },

  TENANT: {
    ALREADY_EXISTS: 'TENANT_001',
    NOT_FOUND: 'TENANT_002',
    INACTIVE: 'TENANT_003',
  },

  USER: {
    NOT_FOUND: 'USER_001',
    EMAIL_ALREADY_EXISTS: 'USER_002',
    ACCOUNT_LOCKED: 'USER_003',
  },

  VALIDATION: {
    INVALID_REQUEST: 'VALIDATION_001',
  },

  SYSTEM: {
    INTERNAL_ERROR: 'SYSTEM_001',
  },

} as const;